# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

argument_specs:  # noqa 701
  main:
    short_description: Install python interpreter
    description:
    - Install python interpreter.

    options:

      state:
        description:
        - The state of python
        type: str
        choices:
        - absent
        - present
        default: present

      version:
        description:
        - Specify the components that you want to install.
        aliases:
          - mafalb_python_version
        type: list
        elements: str
        defaults: _default

...
