# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

- name: Verify ansible
  hosts: all
  vars:
    collection_dir: /root/collections/ansible_collections/mafalb
    virtualenv_basename: ansible-{{ arg_ansible_version }}-py{{ arg_python_version }}
  module_defaults:
    shell:
      executable: /bin/bash

  tasks:
    - name: ansible is in the path
      command: ansible --version
      changed_when: false
      register: __ansible_version
    - name: debug
      debug: var=__ansible_version
    - name: assertions
      assert:
        that:
          - __ansible_version.stdout is match('ansible')
          - __ansible_version.stdout is search(arg_ansible_version|mandatory)
    - name: playbook is present
      copy:
        src: install-ansible.yml
        dest: /root/
        mode: '644'

...
