# vim: set ft=yaml ts=2 expandtab:

# This file is part of Ansible Collection mafalb.ansible
# Copyright (c) 2019-2021 Markus Falb <markus.falb@mafalb.at>
#
# Ansible collection mafalb.ansible is free software: you can redistribute it 
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Ansible collection mafalb.ansible is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Ansible collection mafalb.ansible.
# If not, see <https://www.gnu.org/licenses/>.

---

- name: Verify ansible
  hosts: all

  module_defaults:
    shell:
      executable: /bin/bash

  tasks:

  - name: ansible is in the path
    command: ansible --version
    changed_when: false

  - name: ansible-lint is present
    shell: |
      . ~/.virtualenvs/ansible_lint/bin/activate
      ansible-lint --version
    changed_when: false
    when: ansible_os_family in ['RedHat', 'Rocky']

  - name: ansible-lint is present
    command: ansible-lint --version
    changed_when: false
    when: not ansible_os_family in ['RedHat', 'Rocky']

...
