# vim: set ft=yaml ts=2 expandtab:
---
galaxy_info:
  author: Markus Falb
  description: Ansible role for molecule, ansible testing
  license: GPL-3.0-or-later
  min_ansible_version: "2.10"

  platforms:
    - name: Fedora
      versions:
        - "38"
        - "39"

    - name: EL
      versions:
        - "7"
        - "8"
        - "9"

    - name: Debian
      versions:
        - bullseye
        - bookworm

    - name: Ubuntu
      versions:
        - focal
        - jammy

  galaxy_tags:
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.
    - ansible
    - molecule
    - ci

dependencies: []
