# vim: set ft=yaml ts=2 expandtab:
---

- name: Converge ansible node features
  hosts: t_centos6, t_ubuntuxenial
  roles:

    - role: mafalb.ansible.node
      ansible_node_features:
      - crypto
      - pip

...
