# vim: set ft=yaml ts=2 expandtab:
---

- name: Verify node
  hosts: all
  tasks:

  - name: openssl_privatekey is working
    openssl_privatekey:
      path: /tmp/privatekey

  - name: selinux is working
    copy:
      content: bla
      dest: /tmp/bla.txt
      setype: ssh_home_t
      mode: 0644


- name: verify pip
  hosts: ci-centos8
  tasks:
  - name: pip with virtualenv_command is working
    pip:
      name: six
      virtualenv: "{{ ansible_user_dir }}/.virtualenvs/six"
      virtualenv_command: /usr/bin/python3 -m venv


# no virtualenv for RHEL6, only RHEL7
#
- name: verify pip
  hosts: ci-centos7
  tasks:
  - name: pip with virtualenv_command is working
    pip:
      name: six
      virtualenv: "{{ ansible_user_dir }}/.virtualenvs/six"

- name: verify pip
  hosts: all,!ci-centos7,!ci-centos6
  tasks:
  - name: pip with virtualenv_command is working
    pip:
      name: six
      virtualenv: "{{ ansible_user_dir }}/.virtualenvs/six"
      virtualenv_command: /usr/bin/python3 -m venv


- name: install python 2.7
  hosts: all,!ci-centos8
  tasks:
  - name: python 2.7 is installed
    package:
      name:
      - python

  - name: openssl_privatekey is working
    openssl_privatekey:
      path: /tmp/privatekey

...
