# vim: set ft=yaml ts=2 expandtab:

# This file is part of Ansible Collection mafalb.ansible
# Copyright (c) 2019-2021 Markus Falb <markus.falb@mafalb.at>
#
# Ansible collection mafalb.ansible is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Ansible collection mafalb.ansible is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Ansible collection mafalb.ansible.
# If not, see <https://www.gnu.org/licenses/>.

---

- name: Jmespath is present - {{ virtualenv }}
  ansible.builtin.command: ~/.virtualenvs/{{ virtualenv }}/bin/jp.py -h
  changed_when: false

- name: Tox is present - {{ virtualenv }}
  ansible.builtin.command: ~/.virtualenvs/{{ virtualenv }}/bin/tox --version
  changed_when: false

- name: Testinfra is present - {{ virtualenv }}
  ansible.builtin.command: ~/.virtualenvs/{{ virtualenv }}/bin/py.test --version
  changed_when: false

- name: Pylint is present - {{ virtualenv }}
  ansible.builtin.command: ~/.virtualenvs/{{ virtualenv }}/bin/pylint --version
  changed_when: false

- name: Rstcheck is present - {{ virtualenv }}
  ansible.builtin.command: ~/.virtualenvs/{{ virtualenv }}/bin/rstcheck --version
  changed_when: false

# that that python3 is used
# the output format of molecule --version changed in molecule 3.1.4
#
- name: Python 3 - {{ virtualenv }}
  ansible.builtin.shell: |
    set -o pipefail
    . ~/.virtualenvs/{{ virtualenv }}/bin/activate
    NO_COLOR=1 molecule --version | grep -E "python( |==|:)3"
  changed_when: false

- name: Python 3 - {{ virtualenv }}
  ansible.builtin.shell: |
    set -o pipefail
    ~/.virtualenvs/{{ virtualenv }}/bin/pip --version | grep "python 3"
  changed_when: false

...
