# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

- name: Include OS family specific variables
  ansible.builtin.include_vars: "{{ __file }}"
  with_first_found:
  - "{{ ansible_os_family }}.yml"
  loop_control:
    loop_var: __file

- name: Include OS specific variables
  ansible.builtin.include_vars: "{{ __file }}"
  with_first_found:
  - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  loop_control:
    loop_var: __file

# the content of state was validated in vars.yml
# we need a default for ansible <2.11
#
- name: Include tasks
  ansible.builtin.include_tasks:
    file: "{{ python_state | default('present') }}.yml"

...
