# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

- name: assertions
  assert:
    that:
      - python_package[python_version] is defined

- name: debug
  debug:
    msg: "{{
      [python_package[python_version]]
      + __python_extra_packages[python_version[0]]
    }}"

- name: python is present
  package:
    name: "{{
      [python_package[python_version]]
      + __python_extra_packages[python_version[0]]
    }}"

...
