# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

- name: assertions
  assert:
    that:
      - mafalb_python_package[__mafalb_python_version] is defined

- name: python is present
  package:
    name: "{{
      [mafalb_python_package[__mafalb_python_version]]
      + __mafalb_python_extra_packages[__mafalb_python_version[0]]
    }}"

...
