# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

- hosts: all
  roles:
    - role: mafalb.ansible.virtualenv
      do: constraints
  tasks:
    - name: check for variable presence
      assert:
        that: mafalb_ansible_latest_version is defined

    - name: try to get one version ahead for 2.11
      block:
        - name: create constraints for one version ahead
          include_role:
            name: mafalb.ansible.virtualenv
          vars:
            do: constraints
            mafalb_ansible_version: "{{
              '2.11.' +
              (mafalb_ansible_latest_version['2.11'].split('.')[2]|int + 1)|string }}"
      rescue:
        - name: debug the failed task
          debug: var=ansible_failed_task.action
          register: __reg_failed_action
        - name: debug __reg_failed_action
          debug: var=__reg_failed_action
      always:
        - name: ensure that it has failed
          assert:
            that: __reg_failed_action["ansible_failed_task.action"]|default('') == 'git'
            fail_msg: It seems that there is an unsupported ansible version available.

    - name: try to get one version ahead for 2.10
      block:
        - name: create constraints for one version ahead
          include_role:
            name: mafalb.ansible.virtualenv
          vars:
            do: constraints
            mafalb_ansible_version: "{{
              '2.10.' +
              (mafalb_ansible_latest_version['2.10'].split('.')[2]|int + 1)|string }}"
      rescue:
        - name: debug the failed task
          debug: var=ansible_failed_task.action
          register: __reg_failed_action
        - name: debug __reg_failed_action
          debug: var=__reg_failed_action
      always:
        - name: ensure that it has failed
          assert:
            that: __reg_failed_action["ansible_failed_task.action"]|default('') == 'git'
            fail_msg: It seems that there is an unsupported ansible version available.

    - name: try to get one version ahead for 2.9
      block:
        - name: create constraints for one version ahead
          include_role:
            name: mafalb.ansible.virtualenv
          vars:
            do: constraints
            mafalb_ansible_version: "{{
              '2.9.' +
              (mafalb_ansible_latest_version['2.9'].split('.')[2]|int + 1)|string }}"
      rescue:
        - name: debug the failed task
          debug: var=ansible_failed_task.action
          register: __reg_failed_action
        - name: debug __reg_failed_action
          debug: var=__reg_failed_action
      always:
        - name: ensure that it has failed
          assert:
            that: __reg_failed_action["ansible_failed_task.action"]|default('') == 'git'
            fail_msg: It seems that there is an unsupported ansible version available.

...
