# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

- hosts: all
  tasks:

    - name: get all tags
      command: git ls-remote --tags https://github.com/ansible/ansible
      register: __reg_tags

    - name: check for new 2.9 version
      assert:
        that:
          - not __reg_tags.stdout|regex_search('2.9'|mafalb.ansible.next_version + '$')
        fail_msg: "{{ '2.9'|mafalb.ansible.next_version }} is available" 

    - name: check for new 2.10 version
      assert:
        that:
          - not __reg_tags.stdout|regex_search('2.10'|mafalb.ansible.next_version + '$')
        fail_msg: "{{ '2.10'|mafalb.ansible.next_version }} is available" 

    - name: check for new 2.11 version
      assert:
        that:
          - not __reg_tags.stdout|regex_search('2.11'|mafalb.ansible.next_version + '$')
        fail_msg: "{{ '2.11'|mafalb.ansible.next_version }} is available" 
        
...
