# Copyright (c) Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---
# change this when new version of ansible/ansible-core is released
# also create constraints in files/constraints/ansible-test/
latest_ansible_version:  # noqa var-naming[no-role-prefix]
  "2.9": 2.9.27
  "2.10": 2.10.17
  "2.11": 2.11.12
  "2.12": 2.12.10
  "2.13": 2.13.13
  "2.14": 2.14.14
  "2.15": 2.15.9
  "2.16": 2.16.3

ansible_rc_versions:
  "2.12":
    - 2.12.0rc1

ansible_test_packages:  # noqa var-naming[no-role-prefix]
  "2.9":
    - mock
    - flake8
    - ntlm-auth
    - rstcheck
    - sphinx
    - virtualenv
    - voluptuous
    - yamllint
    - pytest # not supported for python 2
    - pylint # not supported for python 2
    - pytest-mock
    - pytest-xdist
  "2.10":
    - flake8
    - antsibull-changelog
    - pylint
    - resolvelib
    - toml
    - voluptuous
    - yamllint
    - coverage
    - pytest
    - pytest-xdist
    - pytest-mock
    - mock
  "2.11":
    - flake8
    - antsibull-changelog
    - pylint
    - voluptuous
    - yamllint
    - typed-ast
    - pytest
    - junit-xml
    - pytest-xdist
    - pytest-mock
    - mock
  "2.12":
    - flake8
    - mock
    - pytest-mock
    - pytest-xdist
    - pytest-forked
    - py
    - voluptuous
    - wrapt
    - yamllint
  "2.13":
    - flake8
    - mock
    - pytest-mock
    - pytest-xdist
    - pytest-forked
    - py
  "2.14":
    - flake8
    - mock
    - pytest-mock
    - pytest-xdist
    - pytest-forked
    - py
  "2.15":
    - flake8
    - mock
    - pytest-mock
    - pytest-xdist
    - pytest-forked
    - py
  "2.16":
    - flake8
    - mock
    - pytest-mock
    - pytest-xdist
    - pytest-forked
    - py

# https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-changelogs
python_versions:  # noqa var-naming[no-role-prefix]
  "2.9": ["2.7", "3.5", "3.6", "3.7", "3.8"]
  "2.10": ["2.7", "3.5", "3.6", "3.7", "3.8", "3.9"]
  "2.11": ["2.7", "3.5", "3.6", "3.7", "3.8", "3.9"]
  "2.12": ["3.8", "3.9", "3.10"]
  "2.13": ["3.8", "3.9", "3.10"]
  "2.14": ["3.9", "3.10", "3.11"]
  "2.15": ["3.9", "3.10", "3.11"]
  "2.16": ["3.10", "3.11", "3.12"]
