# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

mafalb_ansible_system_dependencies:
- "{{ 'python3-setuptools' if ansible_python.version.major == '3' else 'python-setuptools' }}"
- "{{ 'python3-venv' if ansible_python.version.major == '3' else 'python-virtualenv' }}"
# no wheel, e.g. cffi
- python3-dev
- libffi-dev
- gcc

mafalb_ansible_virtualenv_command:
  2: "virtualenv -p {{ mafalb_ansible_virtualenv_python }}"
  3: "{{ __reg_targeted_python.executable }} -m venv"

mafalb_ansible_default_openssl_version: '1.1'

...
