# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

# change this when new version of ansible/ansible-core is released
# also create constraints in files/constraints/ansible-test/
mafalb_ansible_data:
  latest_version:
    '2.11': '2.11.6'
    '2.10': '2.10.15'
    '2.9': '2.9.27'
  ansible_test_packages:
    '2.10':
      - flake8
      - antsibull-changelog
      - pylint
      - resolvelib
      - toml
      - voluptuous
      - yamllint
    '2.11':
      - flake8
      - antsibull-changelog
      - pylint
      - voluptuous
      - yamllint
    '2.9':
      - flake8
      - ntlm-auth
      - pylint
      - rstcheck
      - sphinx
      - virtualenv
      - voluptuous
      - yamllint

mafalb_ansible_virtualenv_packages:
  pip: '>=20.3,<21.1'
  setuptools: '>41'

mafalb_ansible_virtualenv_command: "{{
  python|default(mafalb_ansible_virtualenv_python) }} -m venv"

# I want to write as simple as:
__mafalb_ansible_version: "{{ packages|default(mafalb_ansible_packages)|mafalb.ansible.latest_ansible_version }}"
__mafalb_ansible_packages: "{{ packages|default(mafalb_ansible_packages)|mafalb.ansible.fix_package_list }}"


...
