# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---


virtualenv_implicit_packages:
  pip: '>=20.3,<21.1'
  setuptools: '>41'

# use absolute path to virtualenv
# https://github.com/ansible/ansible/issues/22967
#
# and use ansible_user_dir
# https://github.com/ansible/ansible/issues/57436
# (~/.virtualenvs/molecule does not work) for
# setting TMPPATH environment variable for pip
#
___virtualenv: "{{
  virtualenv | default('~/.virtualenvs/ansible')
}}"
__virtualenv: "{{ ___virtualenv | regex_replace('^~', ansible_user_dir) }}"

# the path to the python interpreter
# relevant for virtualenvs that already exists
#
__virtualenv_interpreter: "{{
  __virtualenv + '/bin/python'
}}"

# keyed by openssl version
virtualenv_cryptography_specifier:
  '1.0': '<3.2'
  '1.1': '<3.4'

...
