# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

mafalb_ansible_virtualenv_packages:
  pip: '>=20.3,<21.1'
  setuptools: '>41'

# I want to write as simple as:
__mafalb_ansible_majmin_version: "{{ __mafalb_ansible_version.split('.')[0:2]|join('.') }}"
__mafalb_ansible_packages: "{{ mafalb_ansible_packages|default(packages)|mafalb.ansible.fix_package_list(__reg_targeted_python.version.majmin) }}"

mafalb_ansible:
  packages: "{{ packages|default(mafalb_ansible_packages)|default(['_ansible']) }}"

ansible_test_packages_not:
  2:
    - pytest
    - pylint
  3: []

# keyed by openssl version
ansible_cryptography_specifier:
  '1.0': '<3.2'
  '1.1': '<3.4'

...
