# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---
- name: Debug targeted ansible version
  ansible.builtin.debug:
    var: __virtualenv_ansible_version

- name: Get constraints
  delegate_to: localhost
  block:
    - name: Ansible source code is checked out
      ansible.builtin.git:
        repo: https://github.com/ansible/ansible.git
        dest: /tmp/ansible.git
        version: v{{ __virtualenv_ansible_version }}
        # it's very chatty otherwise:
      diff: false
    - name: Get a list of all requirements files
      when: false
      ansible.builtin.find:
        paths: /tmp/ansible.git/test/lib/ansible_test/_data/requirements
        patterns: "*.txt"
      register: __constraints_files
    - name: Debug __constraints_files
      when: false
      ansible.builtin.debug:
        var: __constraints_files
    - name: Get all requirements for ansible 2.9
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          cat *.txt|grep -Ev -e "^git\+" -e "^[^[:space:]]+\\["\
            -e "^paramiko.*python_version >= '2.7'"
        args:
          chdir: /tmp/ansible.git/test/lib/ansible_test/_data/requirements
      changed_when: false
      register: __constraints_29
      when: __mafalb_ansible_version is match('2.9')
    - name: Get all requirements for ansible > 2.9
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          cat *.txt|grep -Ev -e "^git\+" -e "^[^[:space:]]+\\["
        args:
          chdir: /tmp/ansible.git/test/lib/ansible_test/_data/requirements
      changed_when: false
      register: __constraints
      when: __mafalb_ansible_version is not match('2.9')
    - name: Debug __constraints
      ansible.builtin.debug:
        var: __constraints
    # do not replace existing constraints file
    - name: Constraints file for ansible-test is present
      ansible.builtin.copy:
        content: "{{ __constraints.stdout | default(__constraints_29.stdout) }}"
        dest: "{{ role_path }}/files/constraints/ansible-test/v{{ __mafalb_ansible_version }}.txt"
        backup: true
        mode: "0644"
        force: false
      register: __reg_constraints_file
