# vim: set ft=yaml ts=2 expandtab:

# This file is part of Ansible Collection mafalb.ansible
# Copyright (c) 2019-2021,2023 Markus Falb <markus.falb@mafalb.at>
#
# Ansible collection mafalb.ansible is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Ansible collection mafalb.ansible is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Ansible collection mafalb.ansible.
# If not, see <https://www.gnu.org/licenses/>.

---
# molecule - 3.4.* / 2.10.*
# default1 - 6.0.3 / 2.14.3
# default2 - 6 / 2.14

- name: Install different variants of molecule
  hosts: all

  roles:
    - role: mafalb.ansible.python
      python_version: "3.6"

    - role: mafalb.ansible.python
      python_version: "3.9"

    - role: mafalb.ansible.virtualenv
      virtualenv_packages:
        - _ansible_test
        - _ansible
        - ansible-lint
        - molecule

  tasks:
    - name: Prepare default1 - 6.0.3 / 2.14.3
      ansible.builtin.include_role:
        name: mafalb.ansible.virtualenv
      vars:
        virtualenv: ~/.virtualenvs/default1
        virtualenv_python_interpreter: python3.9
        virtualenv_packages:
          - _ansible_test
          - _ansible==2.14.3
          - ansible-lint
          - molecule

    - name: Debug
      ansible.builtin.debug:
        var: virtualenv_python_interpreter

    - name: Prepare default2 - ansible 2.12
      ansible.builtin.include_role:
        name: mafalb.ansible.virtualenv
      vars:
        virtualenv: ~/.virtualenvs/default2
        virtualenv_python_interpreter: python3.9
        virtualenv_packages:
          - _ansible_test
          - _ansible~=2.12.0
          - ansible-lint
          - molecule
