# vim: set ft=yaml ts=2 expandtab:
---

# 1: update ansible 2.9.10 -> 2.9.latest (specify 2.9)
# 2: update ansible 2.9.10 -> 2.9.latest (specify 2.9.*)
# 3: update molecule 3.1.4 -> 3.1.latest (specify 3.1)
# 4: update molecule 3.1.4 -> 3.1.latest (specify 3.1.*)
# 5: update molecule 3.1.4 -> 3
# 6: update molecule 3.1.4 -> 3.2
# 7: update ansible 2.10 to latest
# 8: update ansible 2.10.1 -> 2.10.latest, molecule 3.1.4 -> 3.latest.latest

- name: Converge upgraded
  hosts: all,!t_centos6,!t_ubuntuxenial

  tasks:

  # change the equivalent prepare task in
  # prepare.yml too
  # when changing tasks
  #

  - name: upgrade upgraded1 - 3.1.4 / 2.9.10
    include_role:
      name: mafalb.ansible.molecule
    vars:
      molecule_ansible_version: '2.9'
      molecule_update_ansible: true
      molecule_virtualenv: ~/.virtualenvs/upgraded1

  - name: upgrade upgraded2 - 3.1.4 / 2.9.10
    include_role:
      name: mafalb.ansible.molecule
    vars:
      molecule_ansible_version: '2.9.*'
      ansible_update: true
      molecule_virtualenv: ~/.virtualenvs/upgraded2

  - name: upgrade upgraded3 - 3.1.4 / 2.10.1
    include_role:
      name: mafalb.ansible.molecule
    vars:
      molecule_version: '3.1'
      molecule_update: true
      molecule_virtualenv: ~/.virtualenvs/upgraded3

  - name: upgrade upgraded4 - 3.1.4 / 2.10.1
    include_role:
      name: mafalb.ansible.molecule
    vars:
      molecule_version: '3.1.*'
      molecule_update: true
      molecule_virtualenv: ~/.virtualenvs/upgraded4

  - name: upgrade upgraded5 - 3.1.4 / 2.9.10
    include_role:
      name: mafalb.ansible.molecule
    vars:
      molecule_version: 3
      molecule_update: true
      molecule_ansible_version: '2.9'
      molecule_virtualenv: ~/.virtualenvs/upgraded5

  - name: upgrade upgraded6 - 3.1.4 / 2.9.10
    include_role:
      name: mafalb.ansible.molecule
    vars:
      molecule_version: '3.2'
      molecule_update: true
      molecule_ansible_version: '2.9'
      molecule_virtualenv: ~/.virtualenvs/upgraded6

  - name: upgrade upgraded7 - 3.1.4 / 2.10.1
    include_role:
      name: mafalb.ansible.molecule
    vars:
      molecule_update_ansible: true
      molecule_virtualenv: ~/.virtualenvs/upgraded7

  - name: upgrade upgraded8 - 3.1.4 / 2.10.1
    include_role:
      name: mafalb.ansible.molecule
    vars:
      molecule_update: true
      molecule_update_ansible: true
      molecule_virtualenv: ~/.virtualenvs/upgraded8

...
