# vim: set ft=yaml ts=2 expandtab:
---

- name: Converge molecule with default settings
  hosts: all,!t_centos6,!t_ubuntuxenial

  roles:

  - name: install molecule with default settings
    role: mafalb.ansible.molecule


- name: Converge molecule 2
  hosts: all,!t_centos6,!t_ubuntuxenial
  roles:

- name: Converge molecule with a specific version of ansible
  hosts: all,!t_centos6,!t_ubuntuxenial
  vars:
    ansibles_version: '2.9'

  roles:

    - role: mafalb.ansible.molecule
      molecule_ansible_version: "{{ ansibles_version }}"
      molecule_virtualenv: ~/.virtualenvs/molecule-{{ ansibles_version }}


- name: Converge other ansible node features
  hosts: all
  roles:

    - role: mafalb.ansible.node
      ansible_node_features:
      - crypto
      - pip

...
