# vim: set ft=yaml ts=2 expandtab:
---

- name: log ansible version
  hosts: all
  tasks:
  - shell: echo {{ ansible_version.major }}.{{ ansible_version.minor }} >>/tmp/ci_ansible_versions.log

- name: Converge molecule with default settings
  hosts: all,!t_centos6,!t_ubuntuxenial

  roles:

  - name: install molecule with default settings
    role: mafalb.ansible.molecule


- name: Converge molecule 2
  hosts: all,!t_centos6,!t_ubuntuxenial
  roles:

  - name: install previous version of molecule
    role: mafalb.ansible.molecule
    molecule_major_version: 2
    molecule_virtualenv: ~/.virtualenvs/molecule2


- name: Converge molecule with a specific version of ansible
  hosts: all,!t_centos6,!t_ubuntuxenial
  vars:
    ansibles_version: 2.8

  roles:

    - role: mafalb.ansible.molecule
      molecule_ansible_version: "{{ ansibles_version }}"
      molecule_virtualenv: ~/.virtualenvs/molecule-{{ ansibles_version }}


- name: Converge other ansible node features
  hosts: all
  roles:

    - role: mafalb.ansible.node
      ansible_node_features:
      - crypto
      - pip

...
