# vim: set ft=yaml ts=2 expandtab:
#
# Copyright (c) Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---
# molecule - 3.4.* / 2.10.*
# default1 - 6.0.3 / 2.14.3
# default2 - 6 / 2.14

- name: Install different variants of molecule
  hosts: all

  module_defaults:
    ansible.builtin.apt:
      cache_valid_time: 80400

  roles:
    - role: mafalb.ansible.python
    - role: mafalb.ansible.virtualenv
      virtualenv_packages:
        - _ansible_test
        - _ansible
        - ansible-lint
        - molecule

  tasks:
    - name: Prepare 2.12 with Python 3.10
      ansible.builtin.include_role:
        name: mafalb.ansible.virtualenv
      vars:
        virtualenv: ~/.virtualenvs/default0  # noqa var-naming[no-role-prefix]
        virtualenv_python: python3.10
        virtualenv_packages:
          - _ansible_test
          - _ansible~=2.12.0
          - ansible-lint
          - molecule

    - name: Prepare default1 - 6.0.3 / 2.14.3
      when: false
      ansible.builtin.include_role:
        name: mafalb.ansible.virtualenv
      vars:
        virtualenv: ~/.virtualenvs/default1  # noqa var-naming[no-role-prefix]
        virtualenv_python: python3.9
        virtualenv_packages:
          - _ansible_test
          - _ansible==2.14.3
          - ansible-lint
          - molecule

    - name: Prepare default2 - ansible 2.12
      when: false
      ansible.builtin.include_role:
        name: mafalb.ansible.virtualenv
      vars:
        virtualenv: ~/.virtualenvs/default2  # noqa var-naming[no-role-prefix]
        virtualenv_python: python3.9
        virtualenv_packages:
          - _ansible_test
          - _ansible~=2.12.0
          - ansible-lint
          - molecule
