# vim: set ft=yaml ts=2 expandtab:
---

# molecule - 3.2.* / 2.10.*
# default1 - 3.1.4 / 2.9.10
# default2 - 3.1.5 / 2.9.*
# default3 - 3.1.4 / 2.10.1
# default4 - 3.1.5 / 2.10.*
# default5 - 3.2.0 / 2.9.10
# default6 - 3.2.* / 2.9.*
# default7 - 3.2.0 / 2.10.1

- name: Install different variants of molecule
  hosts: all,!ci-centos6,!ci-ubuntuxenial

  roles:
  - role: mafalb.ansible.molecule

  tasks:

  - name: prepare default1 - 3.1.4 / 2.9.10
    include_role:
      name: mafalb.ansible.molecule
    vars:
      molecule_version: '3.1.4'
      molecule_ansible_version: '2.9.10'
      molecule_virtualenv: ~/.virtualenvs/default1

  - name: prepare default2 - 3.1 / 2.9
    include_role:
      name: mafalb.ansible.molecule
    vars:
      molecule_version: '3.1'
      molecule_ansible_version: '2.9'
      molecule_virtualenv: ~/.virtualenvs/default2

  - name: prepare default3 - 3.1.4 / 2.10.1
    include_role:
      name: mafalb.ansible.molecule
    vars:
      molecule_version: '3.1.4'
      molecule_ansible_version: '2.10.1'
      molecule_virtualenv: ~/.virtualenvs/default3

  - name: prepare default4 - 3.1 / 2.10
    include_role:
      name: mafalb.ansible.molecule
    vars:
      molecule_version: '3.1'
      molecule_ansible_version: '2.10'
      molecule_virtualenv: ~/.virtualenvs/default4

  - name: prepare default5 - 3.2.0 / 2.9.10
    include_role:
      name: mafalb.ansible.molecule
    vars:
      molecule_version: '3.2.0'
      molecule_ansible_version: '2.9.10'
      molecule_virtualenv: ~/.virtualenvs/default5

  - name: prepare default6 - 3.2 / 2.9
    include_role:
      name: mafalb.ansible.molecule
    vars:
      molecule_version: 3
      molecule_ansible_version: '2.9'
      molecule_virtualenv: ~/.virtualenvs/default6

  - name: prepare default7 - 3.2.0 / 2.10.1
    include_role:
      name: mafalb.ansible.molecule
    vars:
      molecule_version: '3.2.0'
      molecule_ansible_version: '2.10.1'
      molecule_virtualenv: ~/.virtualenvs/default7

...
