# vim: set ft=yaml ts=2 expandtab:
---

dependency:
  name: galaxy
driver:
  name: docker

lint: |
  set -e
  ! grep -r "no_log: false" .
  yamllint .
  ansible-lint -v
  ansible-lint -v roles/*/vars/*.yml
  flake8 -v

platforms:
  - name: t_${CI_CONTAINER_IMAGE:-centos}${CI_CONTAINER_TAG:-7}
    image: ${CI_CONTAINER_IMAGE:-centos}:${CI_CONTAINER_TAG:-7}
    dockerfile: ../resources/Dockerfile.j2

provisioner:
  name: ansible
  playbooks:
    side_effect: side_effect.yml
  ansible_args:
    - --tags=all,debug
    - --diff
  lint:
    name: ansible-lint
  env:
    ANSIBLE_COLLECTIONS_PATHS: "../../../../..:~/.ansible/collections"
  config_options:
    defaults:
      interpreter_python: auto

verifier:
  name: ansible
  lint:
    name: ansible-lint
