# vim: set ft=yaml ts=2 expandtab:
---

- name: test collection and role creation
  hosts: all,!t_centos6,!t_ubuntuxenial

  vars:
    virtualenvs:
    - { index: 0, virtualenv: molecule }
    - { index: 1, virtualenv: default1 }
    - { index: 2, virtualenv: default2 }
    - { index: 3, virtualenv: default3 }
    - { index: 4, virtualenv: default4 }
    - { index: 5, virtualenv: default5 }
    - { index: 6, virtualenv: default6 }
    - { index: 7, virtualenv: default7 }

  tasks:

  # kind of quirky
  # copy src files to CI node
  #
  - name: the playbooks and supporting files are present # noqa 208
    copy:
      src: ../../playbooks/{{ item }}
      dest: /tmp/
    loop:
    - collection-init.yml
    - role-init.yml
    - files
    - templates

  - name: test collection and role creation
    include_tasks: test_playbooks.yml
    loop: "{{ virtualenvs[:2]|map(attribute='virtualenv')|list }}"
    loop_control:
      loop_var: _ansibleversion

...
