# vim: set ft=yaml ts=2 expandtab:
---

- name: remove existing collection role
  file:
    path: /tmp/molecule-{{ _ansibleversion }}
    state: absent

- name: a test collection is initialized # noqa 301
  shell: |
    . ~/.virtualenvs/{{ _ansibleversion }}/bin/activate
    mkdir -p /tmp/molecule-{{ _ansibleversion }}
    cd /tmp/molecule-{{ _ansibleversion }}
    ansible-playbook /tmp/collection-init.yml -e collection=tests.testcollection

- name: a test role is initialized (collection role) # noqa 301
  shell: |
    . ~/.virtualenvs/{{ _ansibleversion }}/bin/activate
    cd /tmp/molecule-{{ _ansibleversion }}/tests/testcollection/roles
    ansible-playbook /tmp/role-init.yml -e role=tests.testcollection.testrole -e "author='bla <blubb@example.com>'"

- name: a test role is initialized (standalone) # noqa 301
  shell: |
    . ~/.virtualenvs/{{ _ansibleversion }}/bin/activate
    cd /tmp/molecule-{{ _ansibleversion }}
    ansible-playbook /tmp/role-init.yml -e role=tests.testrole -e "author='bla <blubb@example.com>'"

...
