# vim: set ft=yaml ts=2 expandtab:
---

- name: Verify molecule
  hosts: all
  vars:
    ansible:
      versions:
      - ''
      - '2.9.9'
      - '2.9'

  module_defaults:
    shell:
      executable: /bin/bash

  tasks:

  - name: get locale
    changed_when: false
    command: locale
    register: _locale

  - debug: var=_locale

  - name: ansible is present - molecule
    shell: |
      . ~/.virtualenvs/molecule{{ item }}/bin/activate
      ansible --version
    changed_when: false
    loop: "{{ ansible.versions }}"
    register: _ansibles_version

  - name: molecule is present - molecule
    shell: |
      . ~/.virtualenvs/molecule{{ item }}/bin/activate
      molecule --version
    changed_when: false
    loop: "{{ ansible.versions }}"
    register: _molecules_ansible_version

  - name: verify molecule installation
    include_tasks: verify_molecule.yml
    loop: "{{ ansible.versions }}"
    loop_control:
      loop_var: _ansibleversion

  - name: assertions
    assert:
      that:
      - _ansibles_version.results[0].stdout_lines[0] is match('ansible')
      - _ansibles_version.results[0].stdout_lines[0] is match('ansible 2.10.*')
      - _ansibles_version.results[1].stdout_lines[0] is match('ansible 2.9.9')
      - _ansibles_version.results[2].stdout_lines[0] is match('ansible 2.9.*')
      - _ansibles_version.results[2].stdout_lines[0].split()[1] is version(_ansibles_version.results[1].stdout_lines[0].split()[1], '>')
      - _ansibles_version.results[2].stdout_lines[0].split()[1] is version('2.10', '<')

...
