# vim: set ft=yaml ts=2 expandtab:
---

- name: Verify molecule
  hosts: all
  vars:
    ansible:
      versions:
      - ''
      - '2.9'
      - '2.9.9'

  tasks:

  - name: get locale
    changed_when: false
    command: locale
    register: _locale

  - debug: var=_locale

  - name: ansible is present
    shell: |
      set -o pipefail
      . ~/.virtualenvs/molecule{{ item }}/bin/activate
      ansible --version
    changed_when: false
    loop: "{{ ansible.versions }}"
    register: _ansibles_version

  - name: molecule is present
    shell: |
      set -o pipefail
      . ~/.virtualenvs/molecule{{ item }}/bin/activate
      molecule --version
    changed_when: false
    loop: "{{ ansible.versions }}"
    register: _molecules_ansible_version

  - name: verify molecule installation
    include_tasks:
      file: verify_molecule.yml
    loop: "{{ ansible.versions }}"
    loop_control:
      loop_var: _ansibleversion

  - debug: var=_ansibles_version

  - name: assertions
    assert:
      that:
      - _ansibles_version.results[0].stdout is match('ansible')
      - _ansibles_version.results[0].stdout is match('ansible 2.10.*')
      - _ansibles_version.results[1].stdout is match('ansible 2.9.*')
      - _ansibles_version.results[2].stdout is match('ansible 2.9.9')

...
