# vim: set ft=yaml ts=2 expandtab:
---

- name: "tox is present - {{ item[1] }}{{ item[0] }}"
  command: ~/.virtualenvs/{{ item[1] }}{{ item[0] }}/bin/tox --version
  changed_when: false

- name: testinfra is present - {{ item[1] }}{{ item[0] }}
  command: ~/.virtualenvs/{{ item[1] }}{{ item[0] }}/bin/py.test --version
  changed_when: false

# that that python3 is used
# the output format of molecule --version changed in molecule 3.1.4
#
- name: python 3 - {{ item[1] }}{{ item[0] }}
  shell: |
    set -o pipefail
    . ~/.virtualenvs/{{ item[1] }}{{ item[0] }}/bin/activate
    NO_COLOR=1 molecule --version|grep -E "python( |==|:)3"
  changed_when: false

- name: python 3 - {{ item[1] }}{{ item[0] }}
  shell: |
    set -o pipefail
    ~/.virtualenvs/{{ item[1] }}{{ item[0] }}/bin/pip --version|grep "python 3"
  changed_when: false

...
