# vim: set ft=yaml ts=2 expandtab:

# This file is part of Ansible Collection mafalb.ansible
# Copyright (c) 2019-2021 Markus Falb <markus.falb@mafalb.at>
#
# Ansible collection mafalb.ansible is free software: you can redistribute it 
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Ansible collection mafalb.ansible is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Ansible collection mafalb.ansible.
# If not, see <https://www.gnu.org/licenses/>.

---

- name: CI for custom filters
  hosts: localhost
  tasks:
  - name: debug
    debug: msg="{{ '2.9'|semver }}"
  - name: assertions for custom filters
    assert:
      that:
      - "'3.1.4'|pipver == '3.1.4'"
      - "'3.1'|pipver == '3.1.*'"
      - "'3'|pipver == '3.*'"
      - "3|pipver == '3.*'"
      - "3|semver == '3.0.0'"
      - "'3'|semver == '3.0.0'"
      - "'3.1'|semver == '3.1.0'"
      - "'3.1.4'|semver == '3.1.4'"

- name: Verify molecule
  hosts: all,!ci-centos6,!ci-ubuntuxenial

  module_defaults:
    shell:
      executable: /bin/bash

  vars:
    files:
    - tests/testcollection/galaxy.yml
    - tests/testcollection/roles/testrole/README.md
    - tests.testrole/README.md
    virtualenvs:
    - { index: 0, virtualenv: molecule }
    - { index: 1, virtualenv: default1 }
    - { index: 2, virtualenv: default2 }
    - { index: 3, virtualenv: default3 }
    - { index: 4, virtualenv: default4 }
    - { index: 5, virtualenv: default5 }
    - { index: 6, virtualenv: default6 }
    - { index: 7, virtualenv: default7 }

  tasks:

  - name: get locale
    changed_when: false
    command: locale
    register: _locale

  - name: debug
    debug: var=_locale

  - name: molecule is present - molecule
    shell: |
      . ~/.virtualenvs/{{ item.virtualenv }}/bin/activate
      molecule --version
    changed_when: false
    loop: "{{ virtualenvs }}"
    register: _molecules_version

  - name: debug
    debug: var=_molecules_version
  - name: debug
    debug: var=_molecules_version.results[4].stdout_lines[1].split()[0].split(':')[1]
    when: false

  - name: correct version of ansible/molecule is installed
    assert:
      that:

      - _molecules_version.results[0].stdout_lines[1] is match('    ansible:2.10.')
      - _molecules_version.results[0].stdout_lines[0].split()[1] is match('3.2')

      - _molecules_version.results[1].stdout_lines[1] is match('    ansible:2.9.10')
      - _molecules_version.results[1].stdout_lines[0].split()[1] is version('3.1.4','=')

      - _molecules_version.results[2].stdout_lines[1] is match('    ansible:2.9.')
      - _molecules_version.results[2].stdout_lines[0].split()[1] is version('3.1.5','=')

      - _molecules_version.results[3].stdout_lines[1] is match('    ansible:2.10.')
      - _molecules_version.results[3].stdout_lines[1].split()[0].split(":")[1] is version('2.10.2', '=')
      - _molecules_version.results[3].stdout_lines[0].split()[1] is version('3.1.4','=')

      - _molecules_version.results[4].stdout_lines[1] is match('    ansible:2.10.')
      - _molecules_version.results[4].stdout_lines[1].split()[0].split(":")[1] is version('2.10.0', '>=')
      - _molecules_version.results[4].stdout_lines[0].split()[1] is version('3.1.5','=')

      - _molecules_version.results[5].stdout_lines[1] is match('    ansible:2.9.10')
      - _molecules_version.results[5].stdout_lines[0].split()[1] is version('3.2.0','=')

      - _molecules_version.results[6].stdout_lines[1] is match('    ansible:2.9.')
      - _molecules_version.results[6].stdout_lines[1].split()[0].split(":")[1] is version('2.9.0', '>=')
      - _molecules_version.results[6].stdout_lines[0].split()[1] is version('3.2.0','>=')

      - _molecules_version.results[7].stdout_lines[1] is match('    ansible:2.10.2')
      - _molecules_version.results[7].stdout_lines[1].split()[0].split(":")[1] is version('2.10.2', '=')
      - _molecules_version.results[7].stdout_lines[0].split()[1] is version('3.2.0','=')

  - name: verify molecule installation
    include_role:
      name: verify_molecule
    vars:
      virtualenv: "{{ item.virtualenv }}"
    loop: "{{ virtualenvs }}"


  - name: assert that we do not use reserved variable names
    assert:
      that:
      - collection is not defined
      - role is not defined
      - galaxy_namespace is not defined
      - author is not defined
      - skeleton_path is not defined
      - license is not defined

  - name: debug
    debug: msg="{{ virtualenvs|map(attribute='virtualenv')|product(files)|list }}"

...
