# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Debug targeted ansible version
      ansible.builtin.debug:
        msg: doing {{ arg_ansible_version }} on {{ arg_python_version }}
  roles:
    - role: mafalb.ansible.python
      version: "{{ arg_python_version|default('_default') }}"
    - role: mafalb.ansible.virtualenv
      virtualenv: ~/.virtualenvs/ansible-{{ arg_ansible_version }}-py{{ arg_python_version }}
      python: python{{ arg_python_version }}
      mafalb_ansible_packages:
        - _ansible=={{ arg_ansible_version }}
        - _ansible_test
