# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

- hosts: all
  roles:
    - role: mafalb.ansible.virtualenv
      packages:
        - _ansible
        - molecule[lint,docker,test]~=3.3.4

...
