# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

- hosts: all
  roles:

    - role: mafalb.ansible.virtualenv
      virtualenv: ~/.virtualenvs/ansible29
      mafalb_ansible_version: '2.9'
      mafalb_ansible_packages:
        - _ansible
        - _ansible_test

    - role: mafalb.ansible.virtualenv
      virtualenv: ~/.virtualenvs/ansible210
      mafalb_ansible_version: '2.10'
      mafalb_ansible_packages:
        - _ansible
        - _ansible_test

    - role: mafalb.ansible.virtualenv
      virtualenv: ~/.virtualenvs/ansible211
      mafalb_ansible_version: '2.11'
      mafalb_ansible_packages:
        - _ansible
        - _ansible_test

    - role: mafalb.ansible.virtualenv
      virtualenv: ~/.virtualenvs/molecule29
      mafalb_ansible_version: '2.9'
      mafalb_ansible_packages:
        - _ansible
        - _ansible_test
        - molecule[lint,docker,test]~=3.3.4

    - role: mafalb.ansible.virtualenv
      virtualenv: ~/.virtualenvs/molecule210
      mafalb_ansible_version: '2.10'
      mafalb_ansible_packages:
        - _ansible
        - _ansible_test
        - molecule[lint,docker,test]~=3.3.4

    - role: mafalb.ansible.virtualenv
      virtualenv: ~/.virtualenvs/molecule211
      mafalb_ansible_version: '2.11'
      mafalb_ansible_packages:
        - _ansible
        - _ansible_test
        - molecule[lint,docker,test]~=3.3.4

...
