# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---
- name: Prepare
  hosts: all
  tasks:
    - name: Necessary tools for CI are present
      ansible.builtin.package:
        name:
          - diffutils
          - git
    - name: Special treatment for Ubuntu 18
      when:
        - ansible_distribution == 'Ubuntu'
        - ansible_distribution_major_version == '18'
      block:
        - name: Locale are present
          ansible.builtin.package:
            name: locales
        - name: Generate locale
          community.general.locale_gen:
            name: en_US.UTF-8
