# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

- name: Verify
  hosts: all
  vars:
    collection_dir: /root/collections/ansible_collections/mafalb
    virtualenv_basename: ansible-{{ arg_ansible_version }}-py{{ arg_python_version }}

  module_defaults:
    shell:
      executable: /bin/bash

  tasks:
    - name: Get installed packages for ~/.virtualenvs/ansible
      ansible.builtin.shell: |
        . ~/.virtualenvs/{{ virtualenv_basename }}/bin/activate
        pip freeze >/tmp/{{ virtualenv_basename }}-before.txt
      changed_when: false

    - name: Check major version of targeted python
      block:
        - name: Call targeted python
          ansible.builtin.command: ~/.virtualenvs/{{ virtualenv_basename }}/bin/python --version
          changed_when: false
          register: __reg_virtualenv_python

        - name: Assert that targetet version is the requested
          ansible.builtin.assert:
            that:
              - (__reg_virtualenv_python.stdout is match("Python " + arg_python_version) or
                 __reg_virtualenv_python.stderr is match("Python " + arg_python_version)
                )

    - name: Install requirements # noqa no-changed-when
      ansible.builtin.shell: |
        . ~/.virtualenvs/{{ virtualenv_basename }}/bin/activate
        ansible-test sanity --requirements --python {{ arg_python_version }}
        ansible-test units --requirements --python {{ arg_python_version }}
      args:
        chdir: "{{ collection_dir }}/ansible"

    - name: Get installed packages for ~/.virtualenvs/ansible
      ansible.builtin.shell: |
        . ~/.virtualenvs/{{ virtualenv_basename }}/bin/activate
        pip freeze >/tmp/{{ virtualenv_basename }}-after.txt
      changed_when: false

    - name: Get diff
      ansible.builtin.command: diff -u /tmp/{{ virtualenv_basename }}-before.txt /tmp/{{ virtualenv_basename }}-after.txt
      changed_when: false
      register: __reg_diff

    - name: Diff
      ansible.builtin.debug:
        var: __reg_diff
