# vim: set ft=yaml ts=2 expandtab:

# This file is part of Ansible Collection mafalb.ansible
# Copyright (c) 2019-2021 Markus Falb <markus.falb@mafalb.at>
#
# Ansible collection mafalb.ansible is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Ansible collection mafalb.ansible is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Ansible collection mafalb.ansible.
# If not, see <https://www.gnu.org/licenses/>.

---
- name: Get OS specific variables
  ansible.builtin.include_vars:
    file: "{{ file }}"
  loop_control:
    loop_var: file
  with_first_found:
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Ansible-lint is present
  ansible.builtin.package:
    name: "{{ ansible_lint_package }}"
  when: ansible_lint_package is defined

- name: Virtualenv_command is defined
  when: virtualenv_command is defined
  block:
    - name: Virtualenv package is present
      ansible.builtin.package:
        name: "{{ virtualenv_package }}"
      when: virtualenv_package is defined

    - name: Epel is present
      when:
        - ansible_lint_needs_epel | default(false) | bool
      ansible.builtin.include_role:
        name: mafalb.epel.release

    - name: Dependency packages are present
      ansible.builtin.package:
        name: "{{ ansible_lint_dependency_packages }}"
      when: ansible_lint_dependency_packages is defined

    # ansible-base is explicitly mentioned, otherwise it is upgraded to the latest
    # possibly causing a mismatch between ansible and ansible-base
    #
    - name: Virtualenv is present
      ansible.builtin.pip:
        name:
          - pip>=19.1
          - setuptools>41
          - wheel
        virtualenv: "{{ ansible_lint_virtualenv }}"
        virtualenv_command: "{{ virtualenv_command }}"
        virtualenv_site_packages: true

    - name: Get pip package info
      ansible.builtin.command: "{{ ansible_lint_virtualenv }}/bin/pip show ansible"
      changed_when: false
      register: _pip_package

    - name: Debug
      ansible.builtin.debug:
        var: _pip_package
      tags:
        - never
        - debug

    - name: Assert that ansible is present
      ansible.builtin.assert:
        that:
          - "'Location: /usr/' in _pip_package.stdout"

    - name: Ansible-lint is present
      block:
      # the check for virtualenv is meant as a check for python2
      # ruamel.yaml drops support for python2 in version 17
      # ruamel.yaml.clib dropped support for python2 in version 0.2.3
      #
        - name: Ansible-lint is installed
          ansible.builtin.pip:
            name:
              - ansible-lint<5
              - ruamel.yaml{{ '<0.17' if virtualenv_command == 'virtualenv' else '' }}
              - ruamel.yaml.clib{{ '<0.2.3' if virtualenv_command == 'virtualenv' else '' }}
            extra_args: "{{ '-U eager' if ansible_lint_update is defined else omit }}"
            virtualenv: "{{ ansible_lint_virtualenv }}"
            virtualenv_command: "{{ virtualenv_command }}"
            virtualenv_site_packages: true
