# vim: set ft=yaml ts=2 expandtab:

# This file is part of Ansible Collection mafalb.ansible
# Copyright (c) 2019-2021 Markus Falb <markus.falb@mafalb.at>
#
# Ansible collection mafalb.ansible is free software: you can redistribute it 
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Ansible collection mafalb.ansible is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Ansible collection mafalb.ansible.
# If not, see <https://www.gnu.org/licenses/>.

---

- name: get OS specific variables
  include_vars:
    file: "{{ file }}"
  loop_control:
    loop_var: file
  with_first_found:
  - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"

- name: virtualenv package is present
  package:
    name: "{{ virtualenv_package }}"

# ansible-base is explicitly mentioned, otherwise it is upgraded to the latest
# possibly causing a mismatch between ansible and ansible-base
#
- name: virtualenv is present
  pip:
    name: pip
    extra_args: "{{ '-U eager' if ansible_lint_update is defined else omit }}"
    virtualenv: "{{ ansible_lint_virtualenv }}"
    virtualenv_command: "{{ virtualenv_command }}"
    virtualenv_site_packages: true

- name: get pip package info
  when: false
  pip_package_info:
    clients: "{{ ansible_lint_virtualenv }}/bin/pip"

- name: get pip package info
  command: "{{ ansible_lint_virtualenv }}/bin/pip show ansible"
  changed_when: false
  register: _pip_package

- debug: var=_pip_package
  tags:
  - never
  - debug

- name: assert that ansible is present
  assert:
    that:
    - "'Location: /usr/' in _pip_package.stdout"

- name: ansible-lint is present
  block:

  - name: dependencies for ansible-lint are present
    package:
      name: "{{ virtualenv_package }}"

  # ansible-base is explicitly mentioned, otherwise it is upgraded to the latest
  # possibly causing a mismatch between ansible and ansible-base
  #
  - name: ansible-lint is installed
    pip:
      name: ansible-lint
      extra_args: "{{ '-U eager' if ansible_lint_update is defined else omit }}"
      virtualenv: "{{ ansible_lint_virtualenv }}"
      virtualenv_command: "{{ virtualenv_command }}"
      virtualenv_site_packages: true

...
