# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---
- name: Debug
  ansible.builtin.debug:
    var: target_version | mandatory

- name: Ansible virtualenv is present
  ansible.builtin.include_role:
    name: mafalb.ansible.virtualenv
  vars:
    packages:
      - ansible
      - _ansible=={{ target_version }}
      - _ansible_test
- name: Check version of ansible
  block:
    - name: Get ansible version
      ansible.builtin.command:
        cmd: ~/.virtualenvs/ansible/bin/ansible --version
      changed_when: false
      register: __reg_ansible_version
    - name: Debug ansible version
      ansible.builtin.debug:
        var: __reg_ansible_version
    - name: Assert that ansible version is correct
      ansible.builtin.assert:
        that:
          - (__reg_ansible_version.stdout_lines[0] is search("{{ target_version }}"))
