# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

- name: get OS specific variables
  include_vars:
    file: "{{ file }}"
  loop_control:
    loop_var: file
  with_first_found:
  - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  - "{{ ansible_os_family }}.yml" # for all others

- name: ansible
  block:
    - name: ansible dependencies are present
      package:
        name: "{{ mafalb_ansible_deps[version|default(mafalb_ansible_version)|default(mafalb_ansible_default_version)] }}"
    - name: ansible is present
      package:
        name: "{{ mafalb_ansible_package[version|default(mafalb_ansible_version)|default(mafalb_ansible_default_version)] }}"
  when: "'_ansible' in packages|default(mafalb_ansible_packages)"

- name: ansible-test
  block:
    - name: ansible-test dependencies are present
      package:
        name: "{{ mafalb_ansible_test_deps[version|default(mafalb_ansible_version)|default(mafalb_ansible_default_version)] }}"
    - name: ansible-test is present
      package:
        name: "{{ mafalb_ansible_test_package[version|default(mafalb_ansible_version)|default(mafalb_ansible_default_version)] }}"
  when: "'_ansible_test' in packages|default(mafalb_ansible_packages)"

...
