# vim: set ft=yaml ts=2 expandtab:

# This file is part of Ansible Collection mafalb.ansible
# Copyright (c) 2019-2021 Markus Falb <markus.falb@mafalb.at>
#
# Ansible collection mafalb.ansible is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Ansible collection mafalb.ansible is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Ansible collection mafalb.ansible.
# If not, see <https://www.gnu.org/licenses/>.

---

- name: get OS specific variables
  include_vars:
    file: "{{ file }}"
  loop_control:
    loop_var: file
  with_first_found:
  - "{{ ansible_os_family }}-{{ ansible_distribution }}.yml" # for Fedora
  - "{{ ansible_os_family }}.yml" # for all others

- name: ansibles dependencies are present
  package:
    name: "{{ ansible_dependencies }}"
  when: ansible_dependencies is defined

- name: ansible is present
  package:
    name: "{{ ansible_package }}"

...
