# vim: ft=yaml ts=2 expandtab:
---
galaxy_info:
  author: Markus Falb
  description: Ansible role for ansible node dependencies
  license: GPL-3.0-or-later
  min_ansible_version: "2.10"

  platforms:
    - name: Fedora
      versions:
        - "38"
        - "39"

    - name: EL
      versions:
        - "7"
        - "8"
        - "9"

    - name: Debian
      versions:
        - bullseye
        - bookworm

    - name: Ubuntu
      versions:
        - focal
        - jammy

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  # Optionally specify the branch Galaxy will use when accessing the GitHub
  # repo for this role. During role install, if no tags are available,
  # Galaxy will use this branch. During import Galaxy will access files on
  # this branch. If Travis integration is configured, only notifications for this
  # branch will be accepted. Otherwise, in all cases, the repo's default branch
  # (usually master) will be used.
  # github_branch:

  # List tags for your role here, one per line. A tag is a keyword that describes
  # and categorizes the role. Users find roles by searching for tags. Be sure to
  # remove the '[]' above, if you add tags to this list.
  #
  # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
  #       Maximum 20 tags per role.
  galaxy_tags:
    - ansible
    - ansiblenode

dependencies: []
