# vim: set ft=yaml ts=2 expandtab:

# This file is part of Ansible Collection mafalb.ansible
# Copyright (c) 2019-2021 Markus Falb <markus.falb@mafalb.at>
#
# Ansible collection mafalb.ansible is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Ansible collection mafalb.ansible is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Ansible collection mafalb.ansible.
# If not, see <https://www.gnu.org/licenses/>.

---
- name: Assertions
  ansible.builtin.assert:
    that:
      - ansible_node_features|type_debug == 'list'

- name: OS dependent variables
  with_first_found:
    - "{{ ansible_os_family }}-{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
  ansible.builtin.include_vars:
    file: "{{ file }}"
  loop_control:
    loop_var: file

- name: Necessary packages for package manager are installed
  become: true
  ansible.builtin.package:
    name: "{{ ansible_node_dependencies['pkg_mgr'] }}"
    state: present
  when: ansible_os_family == 'Debian'

- name: Necessary packages for selinux are installed
  become: true
  ansible.builtin.package:
    name: "{{ ansible_node_dependencies['selinux'] }}"
    state: present
  when: "'selinux' in ansible_node_features"

- name: Necessary packages for crypto are installed
  become: true
  ansible.builtin.package:
    name: "{{ ansible_node_dependencies['crypto'] }}"
    state: present
  when: "'crypto' in ansible_node_features"

- name: Necessary packages for pip are installed
  become: true
  ansible.builtin.package:
    name: "{{ ansible_node_dependencies['pip'] }}"
    state: present
  when: "'pip' in ansible_node_features"
