# vim: set ft=yaml ts=2 expandtab:

# BSD 3-Clause License
#
# Copyright (c) 2020,2021 Markus Falb <markus.falb@mafalb.at>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

---

- name: jmespath is present - {{ virtualenv }}
  command: ~/.virtualenvs/{{ virtualenv }}/bin/jp.py -h
  changed_when: false

- name: tox is present - {{ virtualenv }}
  command: ~/.virtualenvs/{{ virtualenv }}/bin/tox --version
  changed_when: false

- name: testinfra is present - {{ virtualenv }}
  command: ~/.virtualenvs/{{ virtualenv }}/bin/py.test --version
  changed_when: false

- name: pylint is present - {{ virtualenv }}
  command: ~/.virtualenvs/{{ virtualenv }}/bin/pylint --version
  changed_when: false

- name: rstcheck is present - {{ virtualenv }}
  command: ~/.virtualenvs/{{ virtualenv }}/bin/rstcheck --version
  changed_when: false

# that that python3 is used
# the output format of molecule --version changed in molecule 3.1.4
#
- name: python 3 - {{ virtualenv }}
  shell: |
    set -o pipefail
    . ~/.virtualenvs/{{ virtualenv }}/bin/activate
    NO_COLOR=1 molecule --version|grep -E "python( |==|:)3"
  changed_when: false

- name: python 3 - {{ virtualenv }}
  shell: |
    set -o pipefail
    ~/.virtualenvs/{{ virtualenv }}/bin/pip --version|grep "python 3"
  changed_when: false

...
