# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---
# It may be necessary to specify ANSIBLE_COLLECTIONS_PATHS
# ANSIBLE_COLLECTIONS_PATHS=../../..
- name: Check for unhandled versions of ansible
  hosts: localhost
  tasks:
    - name: Git is present
      ansible.builtin.package:
        name: git

    - name: Get all tags # noqa command-instead-of-module
      ansible.builtin.command: git ls-remote --tags https://github.com/ansible/ansible
      register: __reg_tags
      changed_when: false

    - name: Assert that no new ansible 2.9 version is available
      ansible.builtin.assert:
        that:
          - not __reg_tags.stdout | regex_search('2.9' | mafalb.ansible.next_version + '\n')
        fail_msg: "{{ '2.9' | mafalb.ansible.next_version }} is available"
        success_msg: "{{ '2.9' | mafalb.ansible.next_version }} is not available"

    - name: Assert that no new ansible 2.10 version is available
      ansible.builtin.assert:
        that:
          - not __reg_tags.stdout | regex_search('2.10' | mafalb.ansible.next_version + '\n')
        fail_msg: "{{ '2.10' | mafalb.ansible.next_version }} is available"
        success_msg: "{{ '2.10' | mafalb.ansible.next_version }} is not available"

    - name: Assert that no new ansible 2.11 version is available
      ansible.builtin.assert:
        that:
          - not __reg_tags.stdout | regex_search('2.11' | mafalb.ansible.next_version + '\n')
        fail_msg: "{{ '2.11' | mafalb.ansible.next_version }} is available"
        success_msg: "{{ '2.11' | mafalb.ansible.next_version }} is not available"

    - name: Assert that no new ansible 2.12 version is available
      ansible.builtin.assert:
        that:
          - not __reg_tags.stdout | regex_search('2.12' | mafalb.ansible.next_version + '\n')
        fail_msg: "{{ '2.12' | mafalb.ansible.next_version }} is available"
        success_msg: "{{ '2.12' | mafalb.ansible.next_version }} is not available"

    - name: Assert that no new ansible 2.13 version is available
      ansible.builtin.assert:
        that:
          - not __reg_tags.stdout | regex_search('2.13' | mafalb.ansible.next_version + '\n')
        fail_msg: "{{ '2.13' | mafalb.ansible.next_version }} is available"
        success_msg: "{{ '2.13' | mafalb.ansible.next_version }} is not available"

    - name: Assert that no new ansible 2.14 version is available
      ansible.builtin.assert:
        that:
          - not __reg_tags.stdout | regex_search('2.14' | mafalb.ansible.next_version + '\n')
        fail_msg: "{{ '2.14' | mafalb.ansible.next_version }} is available"
        success_msg: "{{ '2.14' | mafalb.ansible.next_version }} is not available"

    - name: Assert that no new ansible 2.15 version is available
      ansible.builtin.assert:
        that:
          - not __reg_tags.stdout | regex_search('2.15' | mafalb.ansible.next_version + '\n')
        fail_msg: "{{ '2.15' | mafalb.ansible.next_version }} is available"
        success_msg: "{{ '2.15' | mafalb.ansible.next_version }} is not available"
