# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

# It may be necessary to specify ANSIBLE_COLLECTIONS_PATHS
# ANSIBLE_COLLECTIONS_PATHS=../../..
- hosts: localhost
  tasks:

    - name: git is present
      package:
        name: git

    - name: get all tags  # noqa command-instead-of-module 303
      command: git ls-remote --tags https://github.com/ansible/ansible
      register: __reg_tags
      changed_when: false

    - name: assert that no new ansible 2.9 version is available
      assert:
        that:
          - not __reg_tags.stdout|regex_search('2.9'|mafalb.ansible.next_version + '$')
        fail_msg: "{{ '2.9'|mafalb.ansible.next_version }} is available"
        success_msg: "{{ '2.9'|mafalb.ansible.next_version }} is not available"

    - name: assert that no new ansible 2.10 version is available
      assert:
        that:
          - not __reg_tags.stdout|regex_search('2.10'|mafalb.ansible.next_version + '$')
        fail_msg: "{{ '2.10'|mafalb.ansible.next_version }} is available"
        success_msg: "{{ '2.10'|mafalb.ansible.next_version }} is not available"

    - name: assert that no new ansible 2.11 version is available
      assert:
        that:
          - not __reg_tags.stdout|regex_search('2.11'|mafalb.ansible.next_version + '$')
        fail_msg: "{{ '2.11'|mafalb.ansible.next_version }} is available"
        success_msg: "{{ '2.11'|mafalb.ansible.next_version }} is not available"

    - name: assert that no new ansible 2.12 version is available
      assert:
        that:
          - not __reg_tags.stdout|regex_search('2.11'|mafalb.ansible.next_version + '$')
        fail_msg: "{{ '2.12'|mafalb.ansible.next_version }} is available"
        success_msg: "{{ '2.12'|mafalb.ansible.next_version }} is not available"

...
