# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

- hosts: localhost
  pre_tasks:
    - assert:
        that: version is defined
  roles:
    - role: mafalb.ansible.virtualenv
      do: constraints
      mafalb_ansible_version: "{{ version }}"

...
