# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

- hosts: localhost
  pre_tasks:
    - name: assert that version is defined
      assert:
        that: version is defined
  roles:
    - role: mafalb.ansible.virtualenv
      do: constraints
      packages:
      - _ansible==2.12.0rc1

...
