# Copyright (c) 2019-2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

- name: Install ansible
  hosts: localhost
  pre_tasks:
  - name: Debug
    ansible.builtin.debug:
      var: mafalb_ansible_virtualenv_command|default(true)
  roles:
    - role: mafalb.ansible.virtualenv
      virtualenv_packages: "{{ virtualenv_packages }}"

...
