# Copyright (c) Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---
- name: Install ansible
  hosts: localhost
  pre_tasks:
    - name: Debug
      tags:
        - never
        - debug
      block:
        - name: Debug virtualenv_packages
          ansible.builtin.debug:
            var: virtualenv_packages
        - name: Debug type of virtualenv_packages
          ansible.builtin.debug:
            msg: "{{ virtualenv_packages|type_debug }}"

  roles:

    - role: mafalb.ansible.virtualenv
      when: python_interpreter is defined
      vars:
        virtualenv_packages: "{{ virtualenv_packages }}"
        virtualenv_python: "{{ python_interpreter }}"

    - role: mafalb.ansible.virtualenv
      when: python_interpreter is not defined
      vars:
        virtualenv_packages: "{{ virtualenv_packages }}"
...
