# Copyright (c) 2019-2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

- hosts: localhost
  roles:

    # this is used if molecule_ansible_version is argument
    - role: mafalb.ansible.virtualenv
      virtualenv: ~/.virtualenv/molecule
      mafalb_ansible_version: "{{ molecule_ansible_version }}"
      mafalb_vir
      packages:
        - molecule[lint,docker,test]
        - _ansible
      when: molecules_ansible_version is defined
  
    # this is used if molecule_ansible_version is not argument
    - role: mafalb.ansible.virtualenv
      virtualenv: ~/.virtualenv/molecule
      packages:
        - _ansible
        - molecule[lint,docker,test]
      when: molecules_ansible_version is defined

...
