# vim: set ft=yaml ts=2 expandtab:

# This file is part of Ansible Collection mafalb.ansible
# Copyright (c) 2019-2021 Markus Falb <markus.falb@mafalb.at>
#
# Ansible collection mafalb.ansible is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Ansible collection mafalb.ansible is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Ansible collection mafalb.ansible.
# If not, see <https://www.gnu.org/licenses/>.

---

molecule_virtualenv_command: "{{ ansible_python.executable }} -m venv"

# https://github.com/ansible-community/ansible-build-data
#
# ansible community has the following dependencies on ansible base/core
#
#
# 9.2.0 -> ansible-core<2.17, >=2.16.1
# 9.1.0 -> ansible-core<2.17, >=2.16.1
# 9.0.1 -> ansible-core<2.17, >=2.16.0
# 9.0.0 -> ansible-core<2.17, >=2.16.0
# 8.7.0 -> ansible-core<2.16, >=2.15.7
# 8.6.0 -> ansible-core<2.16, >=2.15.6
# 8.5.0 -> ansible-core<2.16, >=2.15.5
# 8.4.0 -> ansible-core<2.16, >=2.15.4
# 8.3.0 -> ansible-core<2.16, >=2.15.3
# 8.2.0 -> ansible-core<2.16, >=2.15.2
# 8.1.0 -> ansible-core<2.16, >=2.15.1
# 8.0.0 -> ansible-core<2.16, >=2.15.0
# 7.7.0 -> ansible-core<2.15, >=2.14.7
# 7.6.0 -> ansible-core<2.15, >=2.14.6
# 7.5.0 -> ansible-core<2.15, >=2.14.5
# 7.4.0 -> ansible-core<2.15, >=2.14.4
# 7.3.0 -> ansible-core<2.15, >=2.14.3
# 7.2.0 -> ansible-core<2.15, >=2.14.2
# 7.1.0 -> ansible-core<2.15, >=2.14.1
# 7.0.0 -> ansible-core<2.15, >=2.14.0
# 6.7.0 -> ansible-core<2.14, >=2.13.7
# 6.6.0 -> ansible-core<2.14, >=2.13.6
# 6.5.0 -> ansible-core<2.14, >=2.13.5
# 6.4.0 -> ansible-core<2.14, >=2.13.4
# 6.3.0 -> ansible-core<2.14, >=2.13.3
# 6.2.0 -> ansible-core<2.14, >=2.13.2
# 6.1.0 -> ansible-core<2.14, >=2.13.1
# 6.0.0 -> ansible-core<2.14, >=2.13.0
# 5.9.0 -> ansible-core<2.13,>=2.12.6
# 5.8.0 -> ansible-core<2.13,>=2.12.5
# 5.7.0 -> ansible-core<2.13,>=2.12.5
# 5.6.0 -> ansible-core<2.13,>=2.12.4
# 5.5.0 -> ansible-core<2.13,>=2.12.3
# 5.4.0 -> ansible-core<2.13,>=2.12.2
# 5.3.0 -> ansible-core<2.13,>=2.12.2
# 5.2.0 -> ansible-core<2.13,>=2.12.1
# 5.1.0 -> ansible-core<2.13,>=2.12.1
# 5.0.1 -> ansible-core<2.13,>=2.12.0
# 5.0.0 -> ansible-core<2.13,>=2.12.0
# 4.10.0 -> ansible-core<2.12,>=2.11.7
# 4.9.0 -> ansible-core<2.12,>=2.11.6
# 4.8.0 -> ansible-core<2.12,>=2.11.6
# 4.7.0 -> ansible-core<2.12,>=2.11.6
# 4.6.0 -> ansible-core<2.12,>=2.11.5
# 4.5.0 -> ansible-core<2.12,>=2.11.4
# 4.4.0 -> ansible-core<2.12,>=2.11.3
# 4.3.0 -> ansible-core<2.12,>=2.11.3
# 4.2.0 -> ansible-core<2.12,>=2.11.2
# 4.1.0 -> ansible-core<2.12,>=2.11.1
# 4.0.0 -> ansible-core<2.12,>=2.11.0
# 3.4.0 -> ansible-base<2.11,>=2.10.9
# 3.3.0 -> ansible-base<2.11,>=2.10.8
# 3.2.0 -> ansible-base<2.11,>=2.10.7
# 3.1.0 -> ansible-base<2.11,>=2.10.5
# 3.0.0 -> ansible-base<2.11,>=2.10.5
# 2.10.7 -> ansible-base<2.11,>=2.10.5
# 2.10.6 ->ansible-base<2.11,>=2.10.5
# 2.10.5 ->ansible-base<2.11,>=2.10.4
# 2.10.4 ->ansible-base<2.11,>=2.10.3
# 2.10.3 ->ansible-base<2.11,>=2.10.3
# 2.10.2 ->ansible-base<2.11,>=2.10.3
# 2.10.1 ->ansible-base<2.11,>=2.10.2
# 2.10.0 ->ansible-base<2.11,>=2.10.1
#
# i reverse that and get
#
ansible_packages:
  '2.9.0': 'ansible==2.9.0'
  '2.9.1': 'ansible==2.9.1'
  '2.9.2': 'ansible==2.9.2'
  '2.9.3': 'ansible==2.9.3'
  '2.9.4': 'ansible==2.9.4'
  '2.9.5': 'ansible==2.9.5'
  '2.9.6': 'ansible==2.9.6'
  '2.9.7': 'ansible==2.9.7'
  '2.9.8': 'ansible==2.9.8'
  '2.9.9': 'ansible==2.9.9'
  '2.9.10': 'ansible==2.9.10'
  '2.9.11': 'ansible==2.9.11'
  '2.9.12': 'ansible==2.9.12'
  '2.9.13': 'ansible==2.9.13'
  '2.9.14': 'ansible==2.9.14'
  '2.9.15': 'ansible==2.9.15'
  '2.9.16': 'ansible==2.9.16'
  '2.9.17': 'ansible==2.9.17'
  '2.9.18': 'ansible==2.9.18'
  '2.9.19': 'ansible==2.9.19'
  '2.9.20': 'ansible==2.9.20'
  '2.9.21': 'ansible==2.9.21'
  '2.9.22': 'ansible==2.9.22'
  '2.9.23': 'ansible==2.9.23'
  '2.9.24': 'ansible==2.9.24'
  '2.9.25': 'ansible==2.9.25'
  '2.9.*': 'ansible>=2.9.10,<2.10'
  '2.10.0': 'ansible-base==2.10.0'
  '2.10.1': 'ansible-base==2.10.1,ansible<2.10.1'
  '2.10.2': 'ansible-base==2.10.2,ansible<2.10.2'
  '2.10.3': 'ansible-base==2.10.3,ansible<2.10.5'
  '2.10.4': 'ansible-base==2.10.4,ansible<2.10.6'
  '2.10.5': 'ansible-base==2.10.5,ansible<3.2.0'
  '2.10.6': 'ansible-base==2.10.6,ansible<3.2.0'
  '2.10.7': 'ansible-base==2.10.7,ansible<3.3.0'
  '2.10.8': 'ansible-base==2.10.8,ansible<3.4.0'
  '2.10.9': 'ansible-base==2.10.9,ansible<4'
  '2.10.10': 'ansible-base==2.10.10,ansible<4'
  '2.10.11': 'ansible-base==2.10.11,ansible<4'
  '2.10.12': 'ansible-base==2.10.12,ansible<4'
  '2.10.13': 'ansible-base==2.10.13,ansible<4'
  '2.10.14': 'ansible-base==2.10.14,ansible<4'
  '2.10.15': 'ansible-base==2.10.15,ansible<4'
  '2.10.16': 'ansible-base==2.10.16,ansible<4'
  '2.10.*': 'ansible-base>=2.10.9,ansible<4.0.0'
  '2.11.0': 'ansible-core==2.11.0,ansible<4.1.0'
  '2.11.1': 'ansible-core==2.11.1,ansible<4.2.0'
  '2.11.2': 'ansible-core==2.11.2,ansible<4.3.0'
  '2.11.3': 'ansible-core==2.11.3,ansible<4.5.0'
  '2.11.4': 'ansible-core==2.11.4,ansible<4.6.0'
  '2.11.5': 'ansible-core==2.11.5,ansible<4.7.0'
  '2.11.6': 'ansible-core==2.11.6,ansible<4.10.0'
  '2.11.7': 'ansible-core==2.11.7,ansible<5'
  '2.11.8': 'ansible-core==2.11.8,ansible<5'
  '2.11.9': 'ansible-core==2.11.9,ansible<5'
  '2.11.10': 'ansible-core==2.11.10,ansible<5'
  '2.11.11': 'ansible-core==2.11.11,ansible<5'
  '2.11.*': 'ansible-core>2.10,<2.12,ansible<5'
  '2.12.0rc1': 'ansible-core==2.12.0rc1,ansible==5.0.0rc1'
  '2.12.0': 'ansible-core==2.12.0,ansible<5.1.0'
  '2.12.1': 'ansible-core==2.12.1,ansible<5.3.0'
  '2.12.2': 'ansible-core==2.12.2,ansible<5.5.0'
  '2.12.3': 'ansible-core==2.12.3,ansible<5.6.0'
  '2.12.4': 'ansible-core==2.12.4,ansible<5.7.0'
  '2.12.5': 'ansible-core==2.12.5,ansible<5.9.0'
  '2.12.6': 'ansible-core==2.12.6,ansible<6'
  '2.12.*': 'ansible-core~=2.12.0,<2.13,ansible<6'

  '2.13.0': 'ansible-core==2.13.0,ansible<6.1.0'
  '2.13.1': 'ansible-core==2.13.0,ansible<6.2.0'
  '2.13.2': 'ansible-core==2.13.0,ansible<6.3.0'
  '2.13.3': 'ansible-core==2.13.0,ansible<6.4.0'
  '2.13.4': 'ansible-core==2.13.0,ansible<6.5.0'
  '2.13.5': 'ansible-core==2.13.0,ansible<6.6.0'
  '2.13.6': 'ansible-core==2.13.0,ansible<6.7.0'
  '2.13.7': 'ansible-core==2.13.0,ansible<7'
  '2.13.8': 'ansible-core==2.13.0,ansible<7'
  '2.13.9': 'ansible-core==2.13.0,ansible<7'
  '2.13.10': 'ansible-core==2.13.0,ansible<7'
  '2.13.11': 'ansible-core==2.13.0,ansible<7'
  '2.13.12': 'ansible-core==2.13.0,ansible<7'
  '2.13.*': 'ansible-core==2.13.0,ansible<7'

  '2.14.0': 'ansible-core==2.14.0,ansible<7.1.0'
  '2.14.1': 'ansible-core==2.14.1,ansible<7.2.0'
  '2.14.2': 'ansible-core==2.14.2,ansible<7.3.0'
  '2.14.3': 'ansible-core==2.14.3,ansible<7.4.0'
  '2.14.4': 'ansible-core==2.14.4,ansible<7.5.0'
  '2.14.5': 'ansible-core==2.14.5,ansible<7.6.0'
  '2.14.6': 'ansible-core==2.14.6,ansible<7.7.0'
  '2.14.*': 'ansible-core~=2.14.0,ansible<8'

  '2.15.0': 'ansible-core==2.15.0,ansible<8.1.0'
  '2.15.1': 'ansible-core==2.15.1,ansible<8.2.0'
  '2.15.2': 'ansible-core==2.15.2,ansible<8.3.0'
  '2.15.3': 'ansible-core==2.15.2,ansible<8.4.0'
  '2.15.4': 'ansible-core==2.15.2,ansible<8.5.0'
  '2.15.5': 'ansible-core==2.15.2,ansible<8.6.0'
  '2.15.6': 'ansible-core==2.15.2,ansible<8.7.0'
  '2.15.7': 'ansible-core==2.15.2,ansible<8.8.0'
  '2.15.8': 'ansible-core==2.15.2,ansible<8.9.0'
  '2.15.9': 'ansible-core==2.15.2,ansible<8.10.0'
  '2.15.*': 'ansible-core~=2.15.0,ansible<9'

  '2.16.0': 'ansible-core==2.16.0,ansible<9.1.0'
  '2.16.1': 'ansible-core==2.16.1,ansible<9.2.0'
  '2.16.*': 'ansible-core~=2.16.0,ansible<10'


molecule_ansible_major_minor_version: "{{ molecule_ansible_version.split('.')[0:2]|join('.') }}"

molecule_ansible_pip_packages: >
  {{ [ansible_packages[molecule_ansible_version|mafalb.ansible.pipver]] if
     ansible_packages[molecule_ansible_version] is defined else
     [ansible_packages[molecule_ansible_major_minor_version|
       mafalb.ansible.pipver]] }}

ansible_lint_version: "{{ '<5' if molecule_version|mafalb.ansible.pipver is regex('^3.[012]') else '>=5.0.7' }}"
molecule_pip_packages:
- molecule[lint,docker,test]=={{ molecule_version|mafalb.ansible.pipver }}
- ansible-lint{{ ansible_lint_version }}
- jmespath
- tox
- yamllint

ansible_test_packages:
- antsibull-changelog
- resolvelib
- pycodestyle
- yamllint
- pylint
- astroid
- isort
- lazy-object-proxy
- mccabe
- toml
- typed-ast
- wrapt
- voluptuous
- pathspec
- packaging
- rstcheck

...
