# vim: set ft=yaml ts=2 expandtab:
---

name: node-only

on: 
  push:
  schedule:
  - cron: '40 12 * * 6'

jobs:

  node-only:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:

        target:
        - centos6
        - ubuntu-16.04

        os:
        - ubuntu-20.04
        - ubuntu-18.04

        ansible_version:
        - '2.10'
        - '2.9'

        include:

        - target: centos6
          distribution: centos
          version: 6

        - target: centos7
          distribution: centos
          version: 7

        - target: centos8
          distribution: centos
          version: 8

        - target: ubuntu-16.04
          distribution: ubuntu
          version: xenial

        - target: ubuntu-18.04
          distribution: ubuntu
          version: bionic

        - target: ubuntu-20.04
          distribution: ubuntu
          version: focal

        - target: fedora31
          distribution: fedora
          version: 31

        - target: fedora32
          distribution: fedora
          version: 32

    env:
      ANSIBLE_VERSION: ${{ matrix.ansible_version }}
      CI_CONTAINER_IMAGE: ${{ matrix.distribution }}
      CI_CONTAINER_TAG: ${{ matrix.version }}
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1

    defaults:
      run:
        working-directory: ansible_collections/mafalb/ansible

    steps:

      - name: checkout collection ansible
        uses: actions/checkout@v2
        with:
          path: ansible_collections/mafalb/ansible
      
      - name: update apt cache
        run: sudo apt-get update

      - name: install molecule
        run: |
          ansible-playbook -D bootstrap.yml -t all,debug -e molecule_ansible_version=${{ matrix.ansible_version }}
        env:
          ANSIBLE_COLLECTIONS_PATHS: '../../..'

      - name: check ansible version
        run: |
          source ~/.virtualenvs/molecule/bin/activate
          ansible --version | grep "^ansible ${{ matrix.ansible_version }}"

      - name: test playbooks via simple shell scripts
        run: |
          tests/role-init.sh
          tests/collection-init.sh

      - name: molecule tests for playbooks
        run: |
          source ~/.virtualenvs/molecule/bin/activate
          molecule test -s playbooks

      - name: molecule tests for ansible node
        run: |
          source ~/.virtualenvs/molecule/bin/activate
          molecule test -s node

...
