# vim: set ft=yaml ts=2 expandtab:
#
# Copyright (c) 2020-2024 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

name: VERSIONCHECK

on: # yamllint disable-line rule:truthy

  push:
    branches:
    - '**'
    tags-ignore:
    - '*'

  schedule:
  - cron: '07 10 * * *'

jobs:

  check_update:

    runs-on: ubuntu-20.04

    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
      ANSIBLE_COLLECTIONS_PATHS: ../../..

    defaults:
      run:
        working-directory: ansible_collections/mafalb/ansible

    steps:

      - name: checkout collection mafalb.ansible
        uses: actions/checkout@v3
        with:
          path: ansible_collections/mafalb/ansible

      # we are happy with any pre-installed ansible
      - name: check for new versions
        run: ansible-playbook playbooks/check_for_new_version.yml
        env:
          ANSIBLE_COLLECTIONS_PATHS: '../../..'

...
