# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

argument_specs:
  main:
    short_description: Install ansible and related packages via pip
    description:
    - Install ansible and related packages.
    - Install into a python virtualenv.
    - Available componen

    options:

      do:
        description: Define the wanted action
        type: str
        choices:
        - 'constraints'

      state:
        description:
        - The state of ansible
        type: str
        choices:
          - absent
          - present
        default: present

      virtualenv_packages:
        description:
        - Specify the components that you want to install.
        type: list
        elements: str
        default:
          - _ansible

      virtualenv_update:
        description: Update packages in virtualenv.
        type: bool

      virtualenv:
        description: The path to the virtualenv.
        type: path
        default: ~/.virtualenvs/ansible

      virtualenv_python_interpreter:
        description: The path to the python interpreter
        type: path

...
