# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

argument_specs:  # noqa 701
  main:
    short_description: Install ansible and related packages via pip
    description:
    - Install ansible and related packages.
    - Install into a python virtualenv.
    - Available componen

    options:

      do:
        description: Define the wanted action
        type: str
        choices:
        - 'constraints'

      state:
        description:
        - The state of ansible
        type: str
        choices:
        - absent
        - present
        default: present

      mafalb_ansible_packages:
        description:
        - Specify the components that you want to install.
        aliases:
        - packages
        type: list
        elements: str
        default:
        - ansible-core

      mafalb_ansible_update:
        description: Update packages in virtualenv.
        aliases:
        - update
        type: bool

      mafalb_ansible_virtualenv:
        description: The path to the virtualenv.
        aliases:
        - virtualenv
        type: path
        default: ~/.virtualenvs/ansible

      mafalb_ansible_virtualenv_python:
        description: The path to the virtualenv.
        aliases:
        - python
        type: path

...
