# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

galaxy_info:
  author: Markus Falb <markus.falb@mafalb.at>
  description: Ansible role mafalb.ansible.virtualenv
  license: GPL-3.0-or-later
  min_ansible_version: 2.14

  # https://galaxy.ansible.com/api/v1/platforms/
  #
  platforms:
  - name: EL
    versions:
    - 7
    - 8
  - name: Fedora
    versions:
    - 38
  - name: Ubuntu
    versions:
    - xenial
    - bionic
    - focal
    - impish
  - name: Debian
    versions:
    - bookworm

  galaxy_tags:
  - ansible
  - molecule
  - virtualenv

dependencies: []

...
